#!/usr/bin/env bash

sudo apt update && sudo apt upgrade

# What I need
sudo apt install git vim
# wlroots dependencies
sudo apt install meson build-essential ninja-build make cmake

#EGL GLS2
sudo apt install libegl-dev libegl1 libgl-dev libgl1 libgles-dev libgles1 libgles2 libglvnd-core-dev libglvnd-dev libglvnd0 libglx-dev libglx0 libopengl-dev libopengl0

#vulkan
sudo apt install libvulkan-dev libvulkan1 libvulkan-memory-allocator-dev libvulkan-volk-dev mesa-vulkan-drivers  vulkan-tools

# glslang
sudo apt install glslang-dev glslang-tools

# libdrm
sudo apt install libdrm-amdgpu1 libdrm-common libdrm-dev libdrm-radeon1 libdrm-intel1 libdrm-tests libdrm2

# libunput
sudo apt install libinput-bin libinput-dev libinput-tools libinput10

#xkbcommon
sudo apt install libxkbcommon-dev libxkbcommon-doc libxkbcommon-tools libxkbcommon-x11-0 libxkbcommon-x11-dev libxkbcommon0 libxkbregistry-dev libxkbregistry0

# udev
sudo apt install gir1.2-gudev-1.0 libgudev-1.0-0 libgudev-1.0-dev

# pixman
sudo apt install libpixman-1-0 libpixman-1-dev

# libseat
sudo apt install libseat-dev libseat1 seatd

# hwdata
sudo apt install hwdata libdisplay-info-bin libdisplay-info-dev libliftoff-dev libliftoff0

# xorg support
sudo apt install xwayland xwayland-run xwaylandvideobridge

# lbxcb
sudo apt install \
   libxcb-composite0 libxcb-damage0 libxcb-doc libxcb-dpms0 libxcb-dri2-0 libxcb-dri3-0 \
   libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-record0 libxcb-render0 libxcb-res0 \
   libxcb-screensaver0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xf86dri0 libxcb-xfixes0 \
   libxcb-xinerama0 libxcb-xinput0 libxcb-xkb1 libxcb-xtest0 libxcb-xv0 libxcb-xvmc0 \
   libxcb1 \
   libxcb-composite0-dev libxcb-damage0-dev libxcb-dpms0-dev libxcb-dri2-0-dev libxcb-dri3-dev \
   libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-record0-dev libxcb-render0-dev \
   libxcb-res0-dev libxcb-screensaver0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev \
   libxcb-xf86dri0-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xinput-dev libxcb-xkb-dev \
   libxcb-xtest0-dev libxcb-xv0-dev libxcb-xvmc0-dev libxcb1-dev

# libxcb util and errors
sudo apt install libxcb-render-util0 libxcb-render-util0-dev libxcb-errors-dev libxcb-errors0

# wlroots build
bash ~/Git/riverDebian/scipts/wlroots

# River Dependencies
sudo apt install libevdev-dev libevdev-doc libevdev-tools libevdev2
sudo apt install libpkgconf-dev libpkgconf3 pkg-config pkgconf pkgconf-bin scdoc

# user/environment stuff packages
sudo apt install qt6-wayland 

# User Packages
sudo apt install foot wget curl
